### ISSUE TITLE
Content Security - Scripts

### ISSUE THREAD

**Issue by pavanagrawal123** [YunoHost-Apps/nextcloud_ynh#18]
Hi,

I just installed this app into my Yunohost, however on launching the software it's not working because of the content security on the JS scripts. Is this going to be fixed on future releases or do i need to make a configuration change?

**Comment by juliencognito** [comment]
Hello
Same problem on my side; with firefox or chromium. The console view of the firefox's development tools tells me about 'unsafe-eval'.
The files are not displayed until I voluntarily click on 'files'; As long as I am connected, the problem is resolved.
As for the Ynh_Panel, it never appears.

I encounter this problem with NextCloud, not with other applications & not on https://demo.nextcloud.com

Thanks for attention,

Julien

**Comment by Shnoulle** [comment]
Same issue : Content Security Policy on 1st load, reload : all;files are loaded.

My nextcloud are on a subdirectory of my ynh login page.

**Comment by jellium** [comment]
I encounter the same issue.
Below the first of the many errors reported by the browser debug tools:

`Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src 'nonce-S0VxMFBpTEFvcCt4OUIvbXNRMFk0ZWRjUW1zMm9Fa1NJMjRpamhKeVFNOD06UkhMTlVGU3h4TmJWbzJxbDVENTVsNjlwYlQ1NjhSaGdSd3BOK1haRUthRT0=' 'unsafe-eval'”).`

which points to the following line in the source:

`<script nonce="NHNnSzJkYzltV0I3VHpqWldGd00rMHczbkV5MVRSQmVlZjMrMW43RUdkMD06MTc0K2phTm43d3NNWkZhRGQyMGpqQ1pScWlqOUpVWWFRSWpLbmhXSWE2Zz0=" type="text/javascript">`

After refreshing the page once, the problem does not occur and line 55 becomes:

`<script nonce="SUdmWW9iWi9YTlc1U29reVJqMTlXcDZIb3FFRldqTUVzbmJYM1JiS2J5Zz06VEYraHo4QU9PcHpkSGZ4eEV3NGNMTmF5amZSSkMySjIxaEs0cW5MOEJrWT0=" type="text/javascript">`

This behavior is also encountered in the "private browsing" mode of Firefox as well.

**Comment by Shnoulle** [comment]
Tracking done error source (for my error : reload load the scripts)

![capture du 2017-02-15 10-55-40](https://cloud.githubusercontent.com/assets/1439428/22969125/8d2bed24-f36d-11e6-8526-239009af9fb9.png)

**Comment by solarus0** [comment]
Same problem for me, on the first load, I have many CSP errors.
After a refresh, everything works but I still have this warning

`22:20:21,034 Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à https://mail.ultrawaves.fr/ynhpanel.js (« script-src 'nonce-cStYQ3BWWWZFOS9kK2pvTFh4L0RTOUdVNFlaUWpNWG44QXdlTzRjczByOD06eDRhbTVCQk9aTHEva1YxbkUxaWtlcFNqbytJa3dyYUR0R3RvYWQ4ZnAvTT0=' 'unsafe-eval' »). 1 (source inconnue)
`
I think that the resource containing the CS Policy is loaded in the wrong order.
Plus, the policy should include the Yunohost panel (ynhpanel.js).

**Comment by solarus0** [comment]
Here is an extract from the Firefox' debugger on the first load.
![csp error nextcloud ynh](https://cloud.githubusercontent.com/assets/4478496/23173272/efebf252-f858-11e6-966f-0217222f07b0.png)

**Comment by JimboJoe** [comment]
Can you guys try to apply [this PR](https://github.com/YunoHost-Apps/nextcloud_ynh/pull/24)  and see if it changes Nextcloud behavior?
You  only need to swap 2 lines in `/etc/nginx/conf.d/<yourdomain>.d/nextcloud.conf` and reload the configuration with `systemctl reload nginx`.

**Comment by jellium** [comment]
Hi @JimboJoe I just implemented your changes but this did not solve the issue for me (after reloading/restarting nginx, and removing browser downloaded data).

**Comment by Bugsbane** [comment]
I'm still getting:

`Refused to load the script 'https://MYDOMAIN.com/ynhpanel.js' because it violates the following Content Security Policy directive: "script-src 'nonce-UUY3YnN5RFFuazMxMnFLYzc5U1JSNGxpWU1SaXNLTDlLN0tUQzRuMkdaST06RmcrajBscm8rUjI2NHV2YjNPelRMZjAxRnFNRHg0bktic1A5TXVLRWJ1ST0=' 'unsafe-eval'".`

...after applying the update to the Nginx .conf file for Nextcloud and restarting Nginx.

**Comment by JimboJoe** [comment]
Thanks for your tests!
I understand that the YNH tile still doesn't appear, but do you still have to refresh the page at login?

**Comment by Shnoulle** [comment]
Seems working but ......

yunohost / login / nextcloud : have error (maybe issue with browser cache)

yunohots / login / nextcloud : js load , but it take ....... 500ms for each js file ...

![capture du 2017-03-13 12-13-44](https://cloud.githubusercontent.com/assets/1439428/23852110/8a64dfaa-07e6-11e7-8bbc-719bc44b69b0.png)

Aftre : not reload it again.*

But i think i prefer to access to white page, click on logo : it take really less times ;)

**Comment by pavanagrawal123** [comment]
@JimboJoe 
I applied the patch and restarted the Nginx. It doesn't seem to work. I still have to refresh the WebUI once to get all the JS to load.
